### ISSUE TITLE
Add CLI Option to replay with factor (to speed up and slow down)

### ISSUE THREAD

**Issue by OemerYilmazConsiderIT** [consider-it/mqtt-record-replay#11]
In some cases its nice to have a speedfactor to replay the mqtt faster

**Comment by jbeyerstedt** [comment]
Please explain why this feature is needed in more detail. Because I doubt, that the feature would actually solve your issue.

And here are some more reasons, why I don't think, that this feature is a good idea at all:
1. It's really easy to overload the broker or the replay application itself which would result in no timing accuracy at all
2. The replay timing calculations are very complex already with the play/pause functionality
3. It's really likely that our algorithms break when presented with a faster running clock

**Comment by OemerYilmazConsiderIT** [comment]
In usecases where we just need to anayze the Data (without the need for proper Timing) through a long periodt of time a faster replay would be 'nice to have'. But since the reasons you mentioned are likely problematic in the implmentation of it, i dont think its worth to invest time in it. There are probbably other solitions that are more efficient.
I hoped it would be very easy to implement.
